DISCORD_SELECT_OPTION_MAX_LABEL_LENGTH = 100
DISCORD_SELECT_MAX_OPTIONS = 25
DISCORD_EMBED_MAX_FIELDS = 25
DISCORD_AUTOCOMPLETE_MAX_CHOICES = 25

IN_LIBRARY_MARKER = "in Jellyfin"
WISHLIST_MARKER = "wishlisted"
